com:
  environment:
    profile: dev
    db-master-url: jdbc:mysql://localhost:3306/station_info?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=GMT%2B8
    db-master-name: root
    db-master-password: jae7758521
    redis:
      database: 0
      host: localhost
      port: 6379
      password: 123

xxl:
  job:
    admin:
      addresses: http://localhost:9998/xxl-job-admin
    accessToken: 4c317C23d*b41^9AE
    executor:
      appname: yunShuWeightJour
      address:
      ip:
      port: 20248
      logpath: /data/applogs/yunShu/yunShuWeightJour
      logretentiondays: 366